import type { Metadata } from "next";

import "./globals.css";



export const metadata: Metadata = {
  title: "A web app for student time managment",
  description: "Generated by the best fucking developer in earth",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
