export const defaultTabValue: string = "Mathematics"


import { SchoolSubject } from './interface';
export const schoolSubjects: SchoolSubject[] = [
  {
    id: 1,
    name: "Mathematics",
    teacher: "Mr. John Doe",
    lessonsCount: 3,
    averageExamScore: 85,
    completedLessons: 2,
    lessons: [
      {
        lessonId: "math1",
        lessonTitle: "Algebra Basics",
        lessonDescription: "Introduction to algebraic expressions and equations.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Introduction", "Solving Equations", "Practice Problems"],
        lessonTags: ["algebra", "math", "equations"],
        lessonsImgURL: "https://example.com/math1.jpg",
        lessonSubject: "Mathematics",
      },
      {
        lessonId: "math2",
        lessonTitle: "Geometry Fundamentals",
        lessonDescription: "Exploring basic concepts in geometry, including shapes and angles.",
        lessonLongTime: "60 minutes",
        lessonSections: ["Shapes", "Angles", "Pythagorean Theorem"],
        lessonTags: ["geometry", "shapes", "angles"],
        lessonsImgURL: "https://example.com/math2.jpg",
        lessonSubject: "Mathematics",
      },
      {
        lessonId: "math3",
        lessonTitle: "Trigonometry Introduction",
        lessonDescription: "Understanding basic trigonometric functions and their applications.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Sine", "Cosine", "Tangent"],
        lessonTags: ["trigonometry", "math", "functions"],
        lessonsImgURL: "https://example.com/math3.jpg",
        lessonSubject: "Mathematics",
      },
    ],
  },
  {
    id: 2,
    name: "History",
    teacher: "Ms. Sarah Johnson",
    lessonsCount: 3,
    averageExamScore: 90,
    completedLessons: 1,
    lessons: [
      {
        lessonId: "history1",
        lessonTitle: "Ancient Civilizations",
        lessonDescription: "A look into the ancient civilizations and their cultures.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Mesopotamia", "Egypt", "Greece"],
        lessonTags: ["history", "civilizations", "culture"],
        lessonsImgURL: "https://example.com/history1.jpg",
        lessonSubject: "History",
      },
      {
        lessonId: "history2",
        lessonTitle: "World War II",
        lessonDescription: "Study of the major events and impacts of World War II.",
        lessonLongTime: "60 minutes",
        lessonSections: ["Causes", "Major Battles", "Outcomes"],
        lessonTags: ["world war", "history", "war"],
        lessonsImgURL: "https://example.com/history2.jpg",
        lessonSubject: "History",
      },
      {
        lessonId: "history3",
        lessonTitle: "Renaissance",
        lessonDescription: "Exploring the key events and figures of the Renaissance period.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Humanism", "Art", "Science"],
        lessonTags: ["history", "renaissance", "culture"],
        lessonsImgURL: "https://example.com/history3.jpg",
        lessonSubject: "History",
      },
    ],
  },
  {
    id: 3,
    name: "Science",
    teacher: "Dr. Michael Lee",
    lessonsCount: 3,
    averageExamScore: 92,
    completedLessons: 1,
    lessons: [
      {
        lessonId: "science1",
        lessonTitle: "Basic Physics",
        lessonDescription: "Introduction to basic physics concepts such as motion and force.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Motion", "Forces", "Energy"],
        lessonTags: ["physics", "science", "motion"],
        lessonsImgURL: "https://example.com/science1.jpg",
        lessonSubject: "Science",
      },
      {
        lessonId: "science2",
        lessonTitle: "Chemistry Fundamentals",
        lessonDescription: "Exploring basic chemical reactions and the periodic table.",
        lessonLongTime: "60 minutes",
        lessonSections: ["Chemical Reactions", "Periodic Table", "Atoms"],
        lessonTags: ["chemistry", "science", "reactions"],
        lessonsImgURL: "https://example.com/science2.jpg",
        lessonSubject: "Science",
      },
      {
        lessonId: "science3",
        lessonTitle: "Biology Basics",
        lessonDescription: "An introduction to basic biological concepts like cells and organisms.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Cells", "Genetics", "Human Anatomy"],
        lessonTags: ["biology", "science", "cells"],
        lessonsImgURL: "https://example.com/science3.jpg",
        lessonSubject: "Science",
      },
    ],
  },
  {
    id: 4,
    name: "English",
    teacher: "Ms. Emily White",
    lessonsCount: 3,
    averageExamScore: 88,
    completedLessons: 2,
    lessons: [
      {
        lessonId: "english1",
        lessonTitle: "Grammar Essentials",
        lessonDescription: "Learning the basic grammar rules and sentence structures.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Parts of Speech", "Sentence Structure", "Punctuation"],
        lessonTags: ["grammar", "english", "language"],
        lessonsImgURL: "https://example.com/english1.jpg",
        lessonSubject: "English",
      },
      {
        lessonId: "english2",
        lessonTitle: "Literature Analysis",
        lessonDescription: "Introduction to analyzing literary works and their themes.",
        lessonLongTime: "60 minutes",
        lessonSections: ["Reading Comprehension", "Themes", "Character Analysis"],
        lessonTags: ["literature", "analysis", "english"],
        lessonsImgURL: "https://example.com/english2.jpg",
        lessonSubject: "English",
      },
      {
        lessonId: "english3",
        lessonTitle: "Creative Writing",
        lessonDescription: "Exploring the art of storytelling and creative expression through writing.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Narrative Techniques", "Character Development", "Plot Structure"],
        lessonTags: ["writing", "creativity", "english"],
        lessonsImgURL: "https://example.com/english3.jpg",
        lessonSubject: "English",
      },
    ],
  },
  {
    id: 5,
    name: "Physical Education",
    teacher: "Mr. Mark Smith",
    lessonsCount: 3,
    averageExamScore: 82,
    completedLessons: 1,
    lessons: [
      {
        lessonId: "pe1",
        lessonTitle: "Physical Fitness and Exercise Techniques",
        lessonDescription: "An introduction to physical fitness and exercise techniques.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Warm-up", "Cardio", "Strength Training", "Cool-down"],
        lessonTags: ["PE", "fitness", "exercise"],
        lessonsImgURL: "https://example.com/pe1.jpg",
        lessonSubject: "Physical Education",
      },
      {
        lessonId: "pe2",
        lessonTitle: "Team Sports",
        lessonDescription: "Learning the rules and techniques of popular team sports.",
        lessonLongTime: "60 minutes",
        lessonSections: ["Football", "Basketball", "Volleyball", "Teamwork"],
        lessonTags: ["PE", "sports", "teamwork"],
        lessonsImgURL: "https://example.com/pe2.jpg",
        lessonSubject: "Physical Education",
      },
      {
        lessonId: "pe3",
        lessonTitle: "Health and Nutrition",
        lessonDescription: "Understanding the basics of maintaining a healthy lifestyle.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Nutrition", "Exercise", "Healthy Habits"],
        lessonTags: ["health", "nutrition", "PE"],
        lessonsImgURL: "https://example.com/pe3.jpg",
        lessonSubject: "Physical Education",
      },
    ],
  },
  {
    id: 6,
    name: "Art",
    teacher: "Ms. Laura Green",
    lessonsCount: 3,
    averageExamScore: 89,
    completedLessons: 2,
    lessons: [
      {
        lessonId: "art1",
        lessonTitle: "Introduction to Drawing",
        lessonDescription: "Learning the basics of drawing techniques and shading.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Line Drawing", "Shading Techniques", "Composition"],
        lessonTags: ["art", "drawing", "creativity"],
        lessonsImgURL: "https://example.com/art1.jpg",
        lessonSubject: "Art",
      },
      {
        lessonId: "art2",
        lessonTitle: "Painting Techniques",
        lessonDescription: "Exploring various painting methods, from watercolor to acrylics.",
        lessonLongTime: "60 minutes",
        lessonSections: ["Watercolor", "Acrylics", "Brush Techniques"],
        lessonTags: ["art", "painting", "techniques"],
        lessonsImgURL: "https://example.com/art2.jpg",
        lessonSubject: "Art",
      },
      {
        lessonId: "art3",
        lessonTitle: "Sculpture Basics",
        lessonDescription: "Introduction to sculpting with various materials.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Clay Sculpting", "Forming Techniques", "Finishing Touches"],
        lessonTags: ["art", "sculpture", "creativity"],
        lessonsImgURL: "https://example.com/art3.jpg",
        lessonSubject: "Art",
      },
    ],
  },
  {
    id: 7,
    name: "Music",
    teacher: "Ms. Julie Brown",
    lessonsCount: 3,
    averageExamScore: 87,
    completedLessons: 2,
    lessons: [
      {
        lessonId: "music1",
        lessonTitle: "Introduction to Music Theory",
        lessonDescription: "Understanding the basics of music theory, notes, and scales.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Notes", "Scales", "Intervals"],
        lessonTags: ["music", "theory", "learning"],
        lessonsImgURL: "https://example.com/music1.jpg",
        lessonSubject: "Music",
      },
      {
        lessonId: "music2",
        lessonTitle: "Basic Instrumental Skills",
        lessonDescription: "Learning the fundamental techniques for playing instruments.",
        lessonLongTime: "60 minutes",
        lessonSections: ["Guitar", "Piano", "Drums"],
        lessonTags: ["music", "instruments", "skills"],
        lessonsImgURL: "https://example.com/music2.jpg",
        lessonSubject: "Music",
      },
      {
        lessonId: "music3",
        lessonTitle: "Choir and Vocal Techniques",
        lessonDescription: "Learning choir techniques and proper vocal exercises.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Breathing Techniques", "Pitch Control", "Vocal Harmony"],
        lessonTags: ["music", "choir", "vocal"],
        lessonsImgURL: "https://example.com/music3.jpg",
        lessonSubject: "Music",
      },
    ],
  },
  {
    id: 8,
    name: "Languages",
    teacher: "Mr. James White",
    lessonsCount: 3,
    averageExamScore: 91,
    completedLessons: 1,
    lessons: [
      {
        lessonId: "language1",
        lessonTitle: "Spanish Basics",
        lessonDescription: "Introduction to the Spanish language, including vocabulary and grammar.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Vocabulary", "Grammar", "Pronunciation"],
        lessonTags: ["language", "spanish", "vocabulary"],
        lessonsImgURL: "https://example.com/language1.jpg",
        lessonSubject: "Languages",
      },
      {
        lessonId: "language2",
        lessonTitle: "French for Beginners",
        lessonDescription: "Learning basic French phrases and sentence structures.",
        lessonLongTime: "60 minutes",
        lessonSections: ["Vocabulary", "Sentence Structure", "Basic Conversation"],
        lessonTags: ["language", "french", "conversation"],
        lessonsImgURL: "https://example.com/language2.jpg",
        lessonSubject: "Languages",
      },
      {
        lessonId: "language3",
        lessonTitle: "English for ESL Students",
        lessonDescription: "Helping non-native speakers learn English grammar and vocabulary.",
        lessonLongTime: "45 minutes",
        lessonSections: ["Grammar", "Vocabulary", "Pronunciation"],
        lessonTags: ["language", "english", "esl"],
        lessonsImgURL: "https://example.com/language3.jpg",
        lessonSubject: "Languages",
      },
    ],
  },
];
